\set ON_ERROR_STOP on

CREATE ROLE cfi_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE cfi_identity_provisioner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
  NOINHERIT NOREPLICATION BYPASSRLS;
CREATE ROLE cfi_migrator LOGIN PASSWORD :'migrator_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE cfi_runtime LOGIN PASSWORD :'runtime_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
CREATE ROLE cfi_test LOGIN PASSWORD :'test_password'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;

GRANT cfi_owner, cfi_identity_provisioner TO cfi_migrator;
REVOKE cfi_owner, cfi_identity_provisioner FROM cfi_runtime, cfi_test;
GRANT CONNECT ON DATABASE cfi TO cfi_owner, cfi_migrator, cfi_runtime, cfi_test;
GRANT CREATE ON DATABASE cfi TO cfi_owner, cfi_migrator;
GRANT CREATE, USAGE ON SCHEMA public TO cfi_owner, cfi_migrator;
